import js from '@eslint/js';
import jsdoc from 'eslint-plugin-jsdoc';
import globals from 'globals';

export default [
  js.configs.recommended,
  {
    plugins: { jsdoc },
    files: ['**/*.{js,mjs,cjs}'],
    languageOptions: {
      globals: {
        _del: 'readonly',
        _loc: 'readonly',
        _locP: 'readonly',
        _replace: 'readonly',
        $bindable: 'readonly',
        $derived: 'readonly',
        $effect: 'readonly',
        $host: 'readonly',
        $inspect: 'readonly',
        $props: 'readonly',
        $state: 'readonly',
        ActiveEffect: 'readonly',
        Actor: 'readonly',
        AmbientLightDocument: 'readonly',
        AmbientSoundDocument: 'readonly',
        ATLAS: 'readonly',
        AudioContext: 'readonly',
        BONDSMITH: 'readonly',
        CALENDARIA: 'readonly',
        canvas: 'readonly',
        ChatMessage: 'readonly',
        chrisPremades: 'readonly',
        Combat: 'readonly',
        Combatant: 'readonly',
        CompendiumCollection: 'readonly',
        CONFIG: 'readonly',
        CONST: 'readonly',
        d3: 'readonly',
        Dialog: 'readonly',
        dnd5e: 'readonly',
        DONTFORGET: 'readonly',
        f3: 'readonly',
        FilePicker: 'readonly',
        Folder: 'readonly',
        foundry: 'readonly',
        fromUuid: 'readonly',
        fromUuidSync: 'readonly',
        game: 'readonly',
        getDocumentClass: 'readonly',
        GLYPH: 'readonly',
        Handlebars: 'readonly',
        HEROMANCER: 'readonly',
        Hooks: 'readonly',
        Item: 'readonly',
        JournalEntry: 'readonly',
        JournalEntryPage: 'readonly',
        Macro: 'readonly',
        MINSTREL: 'readonly',
        Peddler: 'readonly',
        PIXI: 'readonly',
        Playlist: 'readonly',
        PlaylistSound: 'readonly',
        RegionBehavior: 'readonly',
        RegionDocument: 'readonly',
        Roll: 'readonly',
        RollTable: 'readonly',
        saveAs: 'readonly',
        Scene: 'readonly',
        showdown: 'readonly',
        SPELLBOOK: 'readonly',
        syrinscape: 'readonly',
        Tagger: 'readonly',
        TENACITY: 'readonly',
        TextEditor: 'readonly',
        TileDocument: 'readonly',
        TLC: 'readonly',
        Token: 'readonly',
        TokenDocument: 'readonly',
        TRAVELPACE: 'readonly',
        ui: 'readonly',
        User: 'readonly',
        VGMUSIC: 'readonly',
        vis: 'readonly',
        YT: 'readonly',
        ...globals.browser,
        ...globals.jquery,
        ...globals.node
      },
      ecmaVersion: 'latest',
      sourceType: 'module'
    },
    settings: { jsdoc: { mode: 'jsdoc', preferredTypes: { '.<>': '<>', Object: 'object' }, tagNamePreference: { auguments: 'extends' } } },
    rules: {
      'no-eval': 'error',
      eqeqeq: ['warn', 'smart'],
      'no-var': 'warn',
      'prefer-object-spread': 'warn',
      'prefer-template': 'warn',
      'no-unused-vars': ['warn', { args: 'all', argsIgnorePattern: '^_' }],
      'no-case-declarations': 'off',
      'no-const-assign': 'error',
      'constructor-super': 'error',
      'no-this-before-super': 'error',
      'getter-return': ['warn', { allowImplicit: true }],
      'no-duplicate-imports': ['warn', { includeExports: true }],
      'no-empty': ['warn', { allowEmptyCatch: true }],
      'no-unsafe-optional-chaining': ['warn', { disallowArithmeticOperators: true }],
      'jsdoc/require-jsdoc': [
        'warn',
        {
          require: { FunctionDeclaration: true, MethodDefinition: true, ClassDeclaration: true },
          contexts: [
            'ExportNamedDeclaration > FunctionDeclaration',
            'ExportDefaultDeclaration > FunctionDeclaration',
            'MethodDefinition[static=true]',
            'ClassDeclaration[id.name=/Manager$/] > ClassBody > MethodDefinition',
            'MethodDefinition[key.name=/^handle/]',
            'Property[key.name] > FunctionExpression'
          ],
          exemptEmptyFunctions: false,
          publicOnly: false,
          enableFixer: false
        }
      ],
      'jsdoc/require-param': ['warn', { exemptedBy: ['inheritdoc', 'override'] }],
      'jsdoc/require-param-description': ['warn', { contexts: ['FunctionDeclaration', 'MethodDefinition'] }],
      'jsdoc/require-param-name': 'warn',
      'jsdoc/require-property': 'warn',
      'jsdoc/require-property-name': 'warn',
      'jsdoc/require-returns': ['warn', { contexts: ['FunctionDeclaration', 'MethodDefinition'], exemptedBy: ['inheritdoc', 'override', 'constructor'] }],
      'jsdoc/require-returns-check': 'warn',
      'jsdoc/require-returns-description': ['warn', { contexts: ['FunctionDeclaration', 'MethodDefinition'] }],
      'jsdoc/require-yields': 'warn',
      'jsdoc/require-yields-check': 'warn'
    }
  },
  jsdoc.configs['flat/recommended'],
  { files: ['**/*.mjs'], rules: { 'no-undef': 'error' } },
  { ignores: ['**/node_modules/*', '**/coverage/*', 'dev/**', 'foundry/**', 'dnd5e/**', 'dist/**', '_source/**', 'todo/**'] }
];
